updated github workflow

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -2,6 +2,7 @@ name: CICD
 
 env:
   RUST_MIN_VERSION: "1.56.0"
+  CARGO_TERM_COLOR: always
 
 on:
   push:
@@ -31,7 +32,13 @@ jobs:
       with:
         command: fmt
         args: --all -- --check
-    # TODO: clipy
+
+    # - name: Run clippy
+    #   if: success() || failure()
+    #   uses: actions-rs/cargo@v1
+    #   with:
+    #     command: clippy
+    #     args: -- -D warnings
 
   # TODO: min_version
 
@@ -39,6 +46,7 @@ jobs:
 
   test:
     name: Test
+    needs: [check_fmt_and_clipy]
     runs-on: ${{ matrix.job.os }}
     strategy:
       fail-fast: false
@@ -62,22 +70,15 @@ jobs:
 
   build_and_publish:
     name: Build and Publish (${{ matrix.job.os }}-${{ matrix.job.target }})
+    needs: [test]
     runs-on: ${{ matrix.job.os }}
     strategy:
       fail-fast: false
       matrix:
         job:
-          - { target: aarch64-unknown-linux-gnu   , os: ubuntu-20.04, use-cross: true }
-          - { target: arm-unknown-linux-gnueabihf , os: ubuntu-20.04, use-cross: true }
-          - { target: arm-unknown-linux-musleabihf, os: ubuntu-20.04, use-cross: true }
-          - { target: i686-pc-windows-msvc        , os: windows-2019                  }
-          - { target: i686-unknown-linux-gnu      , os: ubuntu-20.04, use-cross: true }
-          - { target: i686-unknown-linux-musl     , os: ubuntu-20.04, use-cross: true }
-          - { target: x86_64-apple-darwin         , os: macos-10.15                   }
-          - { target: x86_64-pc-windows-gnu       , os: windows-2019                  }
-          - { target: x86_64-pc-windows-msvc      , os: windows-2019                  }
-          - { target: x86_64-unknown-linux-gnu    , os: ubuntu-20.04                  }
-          - { target: x86_64-unknown-linux-musl   , os: ubuntu-20.04, use-cross: true }
+          - { target: x86_64-unknown-linux-musl   , os: ubuntu-latest }
+          - { target: x86_64-apple-darwin , os: macos-latest }
+          - { target: x86_64-pc-windows-msvc, os: windows-latest }
     steps:
     - name: Checkout source code
       uses: actions/checkout@v2
@@ -87,15 +88,13 @@ jobs:
       with:
         toolchain: stable
         profile: default
+        target: ${{ matrix.job.target }}
         default: true
 
-    - name: Install prerequisites
-      shell: bash
+    - name: Install musl tools
+      if : matrix.job.target == 'x86_64-unknown-linux-musl'
       run: |
-        case ${{ matrix.job.target }} in
-          arm-unknown-linux-*) sudo apt-get -y update ; sudo apt-get -y install gcc-arm-linux-gnueabihf ;;
-          aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
-        esac
+        sudo apt install -qq -y musl-tools --no-install-recommends
 
     - name: Extract crate information
       shell: bash
@@ -108,6 +107,26 @@ jobs:
     - name: Build
       uses: actions-rs/cargo@v1
       with:
-        use-cross: ${{ matrix.job.use-cross }}
         command: build
         args: --release --target=${{ matrix.job.target }}
+
+    - name: Package for linux-musl
+      if: matrix.target == 'x86_64-unknown-linux-musl'
+      run: |
+        zip --junk-paths rp-${{ matrix.target }} target/${{ matrix.target }}/release/rp
+
+    - name: Package for windows
+      if: matrix.target == 'x86_64-pc-windows-msvc'
+      run: |
+        powershell Compress-Archive -Path target/${{ matrix.target }}/release/rp.exe -DestinationPath rp-${{ matrix.target }}.zip
+
+    - name: Package for macOS
+      if: matrix.target == 'x86_64-apple-darwin'
+      run: |
+        zip --junk-paths rp-${{ matrix.target }} target/${{ matrix.target }}/release/rp
+
+    - uses: actions/upload-artifact@v2
+      with:
+        name: build-${{ matrix.target }}
+        path: rp-${{ matrix.target }}.zip
+
